### ISSUE TITLE
SFA with intercept only

### ISSUE THREAD

**Issue by arne-henningsen** [hdakpo/sfaR#38]
Currently, sfacross() cannot estimate SFA models with intercept only but it stops with an error message: 

```
est <- sfacross(formula = log(tc/wf) ~ 1, data = utility )
 Error in terms.formula(formula, data = data) : 
  '.' in formula and no 'data' argument 
```

It would be great if sfacross() could estimate SFA models with intercept only, because this is sometimes useful, e.g., when imposing monotonicity with the method suggested by Henningsen & Henning (2009, JPA). Currently one can use the following workaround:

```
utility$ones <- 1
est <- sfacross(formula = log(tc/wf) ~ ones - 1, data = utility )
  Warning message:
  main model is estimated without intercept 
```

Note: the examples above are just for illustration and do not make much sense.

**Comment by hdakpo** [comment]
same as lcmcross
