### ISSUE TITLE
Make the output of logLik.sfacross() consistent with the output of the logLik() methods for models estimated by lm(), glm(), etc.

### ISSUE THREAD

**Issue by arne-henningsen** [hdakpo/sfaR#39]
Currently the output of logLik.sfacross() is quite different from the output of the logLik() methods for models estimated by lm(), glm(), etc. Therefore, methods that rely on logLik() cannot be applied to models that were estimated with sfacross(). Making the output of logLik.sfacross() consistent with the output of the logLik() methods for models estimated by lm(), glm(), etc., will make several other methods applicable to models estimated by sfacross().

**Comment by hdakpo** [comment]
lcmcross too

**Comment by arne-henningsen** [comment]
currently, the `logLik()` method for objects of "`sfacross`" and friends does **not** return an object of class "`logLik`" but writes a character string on the R console

**Comment by arne-henningsen** [comment]
fixed in revision fb4b322907e6e6e0c6509769dacbf9249cb453ff
