### ISSUE TITLE
Calculating efficiency estimates as E[exp(u)] in addition to E[exp(-u)]

### ISSUE THREAD

**Issue by arne-henningsen** [hdakpo/sfaR#41]
The sfaR package can currently calculate estimates of the Shephard efficiency estimates based on production functions and output distance functions as well as the Farrell efficiency estimates based on cost functions and input distance functions, which are E[exp(-u)]. However, it can neither calculate estimates of the Farrell efficiency estimates based on production functions and output distance functions nor the Shephard efficiency estimates based on cost functions and input distance functions, which are E[exp(u)]. As E[exp(u)] is not the same as 1/E[exp(-u)], it would be great if sfaR could also calculate E[exp(u)].

**Comment by hdakpo** [comment]
Use of hcubature for weibull and lognormal
halton draws for gamma dist
