### ISSUE TITLE
Calculate efficiency estimates for observations that were not used to estimate the parameters

### ISSUE THREAD

**Issue by arne-henningsen** [hdakpo/sfaR#42]
The Danish regulators for electricity distribution, (drinking) water supply, and wastewater treatment estimate the frontier (parameters) with a subset of companies and then use the estimated frontier (parameters) to calculate efficiency estimates of all companies (for setting price revenue caps for regulating these natural monopolies). The frontier package can do this, e.g., by 'efficiencies( sfaModel, newdata = allData )'. It would be great if the sfaR package could do the same.

**Comment by hdakpo** [comment]
Including marginal effects of Z on efficiency
