### ISSUE TITLE
Add clustered option for standard error

### ISSUE THREAD

**Issue by hdakpo** [hdakpo/sfaR#53]

**Comment by arne-henningsen** [comment]
I suggest to **not** implement clustered standard errors in the _sfaR_ package but make the _sfaR_ package work with the _sandwich_ package. This would allow the user to use the many options of the sandwich package. As far as I remember, this requires that the _sfaR_ package has `bread()` and `meat()` methods.

**Comment by hdakpo** [comment]
This means that I removed the 'hessianType' option from the function?

**Comment by arne-henningsen** [comment]
No, you should keep argument `hessianType` (with options for analytical, BHHH, and perhaps other options but **not** with an option for a 'robust' Hessian). The calculation of the 'robust' covariance matrix with the _sandwich_ package will then use the Hessian that was calculated as specified by argument `hessianType` (I think through the `bread()` method).
